### ISSUE TITLE
[Question] What is the correct process to update?

### ISSUE THREAD

**Issue by andrasg** [Aterfax/relax-intel-rmrr#24]
Hi,

I am using `5.15.39-3-pve-relaxablermrr` successfully. I now would like to update to the latest kernel. What is the right sequence to update?

My assumption would be:
1. install `5.19.7-2` kernel
2. install patch for `5.19.7-2` kernel
3. pin this kernel version (change the current pinning)
4. reboot

Am I correctly assuming?

**Comment by Aterfax** [comment]
You can simply grab the latest patched kernel debs released which is for your version of Proxmox and install them.

You may need to pin the patched kernel debs depending on the current normal Proxmox kernel version. If the normal Proxmox kernel is more modern you want to boot the older patched kernel thus should pin it.

Reboot.

**Comment by Aterfax** [comment]
Closing this issue as I have added a bit more detailed response in the Q&A discussion here: https://github.com/Aterfax/relax-intel-rmrr/discussions/38
