### ISSUE TITLE
Proxmox 7.3 Kernel doesn't compile

### ISSUE THREAD

**Issue by Netzvamp** [Aterfax/relax-intel-rmrr#27]
Hey,

i've tried to compile the kernel for Proxmox 7.3 (5.19.17) with docker, but it doesn't work.

```
...
WARNING: modpost: vmlinux.o(.text+0xa28e24): Section mismatch in reference from the function i8042_probe() to the variable .init.rodata:i8042_quirks
The function i8042_probe() references
the variable __initconst i8042_quirks.
This is often because i8042_probe lacks a __initconst
annotation or the annotation of i8042_quirks is wrong.

  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  CC      .vmlinux.export.o
  LD      .tmp_vmlinux.btf
  BTF     .btf.vmlinux.bin.o
Killed
  LD      .tmp_vmlinux.kallsyms1
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
  BTFIDS  vmlinux
FAILED: load BTF from vmlinux: No such file or directory
make[2]: *** [Makefile:1171: vmlinux] Error 255
make[2]: *** Deleting file 'vmlinux'
make[2]: Leaving directory '/build/proxmox/proxmox-kernel/pve-kernel/build/ubuntu-kinetic'
make[1]: *** [debian/rules:128: .compile_mark] Error 2
make[1]: Leaving directory '/build/proxmox/proxmox-kernel/pve-kernel/build'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make: *** [Makefile:60: pve-kernel-5.19.17-1-pve-relaxablermrr_5.19.17-1_amd64.deb] Error 2
```

**Comment by Netzvamp** [comment]
I've found a successful build in your build system: https://github.com/Aterfax/relax-intel-rmrr/actions/runs/3551895909 So whatever it is, 5 days ago it was fine. I'll try these builds later on my server.

**Comment by Netzvamp** [comment]
We've upgraded to Proxmox 7.3-3 and the [kernel ](https://github.com/Aterfax/relax-intel-rmrr/actions/runs/3551895909) worked fine.

**Comment by CAVACO-PT** [comment]
Thank you for your work i can confirm  Proxmox 7.3-4 is working on latest !!!

![image](https://user-images.githubusercontent.com/9946471/209994383-285776bb-091e-479d-9a8d-a670ca697e4f.png)

**Comment by docop** [comment]
Thanks for that ! It is working fine ! set the last kernel as previous img above. prox 7.3-4 jan3th update.

**Comment by Aterfax** [comment]
I expect that there was likely some upstream shenanigans at the time causing the downstream compiles to fail. Just added a new release so closing this now.
