### ISSUE TITLE
5.15.104-1-pve and Proxmox 7.4-3

### ISSUE THREAD

**Issue by limehawkmsp** [Aterfax/relax-intel-rmrr#33]
Any update for 5.15.104-1-pve and Proxmox 7.4-3?

**Comment by limehawkmsp** [comment]
build script is crashing
Fetched in submodule path 'submodules/ubuntu-kernel', but it did not contain f384010f9ee2a591f1e725fae5a4efbfbad864b3. Direct fetching of that commit failed

**Comment by Kegelcizer** [comment]
Same issue, tried building from sources in both docker and Proxmox.

**Comment by sarrchri** [comment]
It would seem proxmox's [ubuntu-kernels mirror](https://git.proxmox.com/?p=mirror_ubuntu-kernels.git;a=tags) does not contain such a commit at all, not sure why.
They seem to only have up to 5.15.102-1 in the mirror. Maybe they'll push it later?

I posted a support thread about this on [Proxmox forums](https://forum.proxmox.com/threads/cant-seem-to-build-proxmox-kernel-pve-kernel-5-15-104-1.125359/) just in case this is just an accidental oversight.

**Comment by limehawkmsp** [comment]
> It would seem proxmox's [ubuntu-kernels mirror](https://git.proxmox.com/?p=mirror_ubuntu-kernels.git;a=tags) does not contain such a commit at all. Perhaps since they seem to only have up to 5.15.102-1 in the mirror. Maybe they'll push it later?
> 
> I posted a support thread about this on [Proxmox forums](https://forum.proxmox.com/threads/cant-seem-to-build-proxmox-kernel-pve-kernel-5-15-104-1.125359/) just in case this is just an accidental oversight.

Interesting. I'd assume that's why the build script fails. I have a pretty important server down right now after updating, so I hope they fix it.

**Comment by sarrchri** [comment]
I got a reply on the thread that the mirror was indeed just not up-to-date.
It should now be and building should work again. If you're using self hosted runners, you might have to clear its work folder for it to be able to recover from the error. (At least I had to.)

**Comment by Kegelcizer** [comment]
Looking good now, just finished building.

**Comment by limehawkmsp** [comment]
Thanks for all the help, everyone!

**Comment by limehawkmsp** [comment]
Is there a way to build for this specific kernel? 5.15.104-1
When I run the build script it’s building kernel version 6.2.11-1-pve-relaxablermrr

**Comment by sarrchri** [comment]
@limehawkmsp 
By default, it is not possible. I made changes in my fork quite a while back to make it possible, since I myself use 5.15 kernel.

I'm not sure though how one would go about building the kernel for a commit that's no longer the most recent commit.
I myself built the kernel version 5.15.104-1 two weeks ago and released it on my fork. You're of course free to use it, link below.

https://github.com/sarrchri/relax-intel-rmrr/releases/tag/v5.15.104-1

**Comment by sarrchri** [comment]
I do also have the latest 5.15 kernel (5.15.107-1) built on my fork, you can find it here:
https://github.com/sarrchri/relax-intel-rmrr/actions

It is untested at the moment since I'm not at home right now, though I don't see why it wouldn't work.

**Comment by limehawkmsp** [comment]
You’re awesome, thank you so much for replying! I’m using the kernel in your fork now. It’s working great. Thank you!
