### ISSUE TITLE
[Question] Proxmox 7.4 Kernel

### ISSUE THREAD

**Issue by CAVACO-PT** [Aterfax/relax-intel-rmrr#34]
Hi , @Aterfax  , thank for all your hard work , are you testing still a kernel for proxmox 7.4  ?? , or the 6.1.10 works also with PX7.4 ??

im at 6.1.0-1 , with PX 7.3.4 , just wondering if i should update to 6.1.10 and put PX 7.3.6 because your release notes says its tested , or if theres is anyone with 7.4 with existing kernel that is working ??

whats the recomendation ??

Many thanks keep up the good work !!!

**Comment by Aterfax** [comment]
My node is currently running  7.4-3 with kernel `Linux 6.1.10-1-pve-relaxablermrr`. In general unless you are several major versions behind on the kernel I wouldn't expect any impact on running nodes.

That said, people are free to use the automated builds I've not tested myself from: https://github.com/Aterfax/relax-intel-rmrr/actions/workflows/build-kernel-debs.yml

The latest automated build being `6.2.9-1-pve-relaxablermrr`: https://github.com/Aterfax/relax-intel-rmrr/actions/runs/4642902225

I would expect these builds to be fully functional even if I have not got around to testing them myself yet. I'll probably look at testing the latest kernel relatively soon.

**Comment by CAVACO-PT** [comment]
i choose the safe side , updated to 6.1.10-1 like you  , and updated proxmox , all working fine , thanks for the quick answer 👍 

![image](https://user-images.githubusercontent.com/9946471/230954637-90bfad66-555f-4821-8200-b02812a335d8.png)

Thank you again

**Comment by accessiblepixel** [comment]
I too can confirm that PVE 6.1.10-1 kernel works for me with Proxmox 7.4-3, I kind of accidentally upgraded to it (oops), but it all seems fine. I haven't had much free time to test any of the automatic builds (or mirror them in a few weeks)

**Comment by Aterfax** [comment]
I'll close this now since everything seems to have been answered.
